version: "3.8"

services:
  video-rental-service:
    container_name: video-rental-service
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/ap
      - /app/node_modules
    working_dir: /app
    command: npm run dev
